import type { NextPage } from 'next'
import Head from 'next/head'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import Works from '../components/works'
import TrustedBy from '../components/trsutedbt'

const Home: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead/>
      <AboutUs/>
      <Skills/>
      <Works/>
      <TrustedBy/>
    </div>
  )
}

export default Home
